<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="6" total="6" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Selenium Tests" duration-ms="21627" started-at="2017-08-08T07:11:38Z" finished-at="2017-08-08T07:11:59Z">
    <groups>
    </groups>
    <test name="RentalLog2" duration-ms="14706" started-at="2017-08-08T07:11:38Z" finished-at="2017-08-08T07:11:52Z">
      <class name="ReportGenerationTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:ReportGenerationTest@11531931]" name="setup" is-config="true" duration-ms="6602" started-at="2017-08-08T00:11:38Z" finished-at="2017-08-08T00:11:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:ReportGenerationTest@11531931]" name="initialize" is-config="true" duration-ms="0" started-at="2017-08-08T00:11:44Z" finished-at="2017-08-08T00:11:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="testApp_2()[pri:0, instance:ReportGenerationTest@11531931]" name="testApp_2" duration-ms="4960" started-at="2017-08-08T00:11:44Z" finished-at="2017-08-08T00:11:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at ReportGenerationTest.testApp_2(ReportGenerationTest.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testApp_2 -->
        <test-method status="PASS" signature="clearingSetup()[pri:0, instance:ReportGenerationTest@11531931]" name="clearingSetup" is-config="true" duration-ms="2221" started-at="2017-08-08T00:11:49Z" finished-at="2017-08-08T00:11:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearingSetup -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:ReportGenerationTest@11531931]" name="tearDown" is-config="true" duration-ms="904" started-at="2017-08-08T00:11:52Z" finished-at="2017-08-08T00:11:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ReportGenerationTest -->
    </test> <!-- RentalLog2 -->
    <test name="RentalLosg1" duration-ms="14952" started-at="2017-08-08T07:11:38Z" finished-at="2017-08-08T07:11:53Z">
      <class name="ReportGenerationTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:ReportGenerationTest@ea4a92b]" name="setup" is-config="true" duration-ms="6495" started-at="2017-08-08T00:11:38Z" finished-at="2017-08-08T00:11:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:ReportGenerationTest@ea4a92b]" name="initialize" is-config="true" duration-ms="0" started-at="2017-08-08T00:11:44Z" finished-at="2017-08-08T00:11:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="testApp_1()[pri:0, instance:ReportGenerationTest@ea4a92b]" name="testApp_1" duration-ms="5279" started-at="2017-08-08T00:11:44Z" finished-at="2017-08-08T00:11:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at ReportGenerationTest.testApp_1(ReportGenerationTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testApp_1 -->
        <test-method status="PASS" signature="clearingSetup()[pri:0, instance:ReportGenerationTest@ea4a92b]" name="clearingSetup" is-config="true" duration-ms="2099" started-at="2017-08-08T00:11:50Z" finished-at="2017-08-08T00:11:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearingSetup -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:ReportGenerationTest@ea4a92b]" name="tearDown" is-config="true" duration-ms="1044" started-at="2017-08-08T00:11:52Z" finished-at="2017-08-08T00:11:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ReportGenerationTest -->
    </test> <!-- RentalLosg1 -->
    <test name="RentalLog1" duration-ms="15275" started-at="2017-08-08T07:11:38Z" finished-at="2017-08-08T07:11:53Z">
      <class name="ReportGenerationTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:ReportGenerationTest@6fffcba5]" name="setup" is-config="true" duration-ms="6322" started-at="2017-08-08T00:11:38Z" finished-at="2017-08-08T00:11:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:ReportGenerationTest@6fffcba5]" name="initialize" is-config="true" duration-ms="1" started-at="2017-08-08T00:11:44Z" finished-at="2017-08-08T00:11:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="testApp_1()[pri:0, instance:ReportGenerationTest@6fffcba5]" name="testApp_1" duration-ms="5709" started-at="2017-08-08T00:11:44Z" finished-at="2017-08-08T00:11:50Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at ReportGenerationTest.testApp_1(ReportGenerationTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testApp_1 -->
        <test-method status="PASS" signature="clearingSetup()[pri:0, instance:ReportGenerationTest@6fffcba5]" name="clearingSetup" is-config="true" duration-ms="1861" started-at="2017-08-08T00:11:50Z" finished-at="2017-08-08T00:11:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearingSetup -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:ReportGenerationTest@6fffcba5]" name="tearDown" is-config="true" duration-ms="1372" started-at="2017-08-08T00:11:52Z" finished-at="2017-08-08T00:11:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ReportGenerationTest -->
    </test> <!-- RentalLog1 -->
    <test name="RentalLog4" duration-ms="15372" started-at="2017-08-08T07:11:38Z" finished-at="2017-08-08T07:11:53Z">
      <class name="ReportGenerationTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:ReportGenerationTest@7d417077]" name="setup" is-config="true" duration-ms="5287" started-at="2017-08-08T00:11:38Z" finished-at="2017-08-08T00:11:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:ReportGenerationTest@7d417077]" name="initialize" is-config="true" duration-ms="282" started-at="2017-08-08T00:11:43Z" finished-at="2017-08-08T00:11:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="testApp_3()[pri:0, instance:ReportGenerationTest@7d417077]" name="testApp_3" duration-ms="4751" started-at="2017-08-08T00:11:43Z" finished-at="2017-08-08T00:11:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at ReportGenerationTest.testApp_3(ReportGenerationTest.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testApp_3 -->
        <test-method status="PASS" signature="clearingSetup()[pri:0, instance:ReportGenerationTest@7d417077]" name="clearingSetup" is-config="true" duration-ms="3536" started-at="2017-08-08T00:11:48Z" finished-at="2017-08-08T00:11:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearingSetup -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:ReportGenerationTest@7d417077]" name="tearDown" is-config="true" duration-ms="1489" started-at="2017-08-08T00:11:52Z" finished-at="2017-08-08T00:11:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ReportGenerationTest -->
    </test> <!-- RentalLog4 -->
    <test name="RentalLog3" duration-ms="15607" started-at="2017-08-08T07:11:38Z" finished-at="2017-08-08T07:11:53Z">
      <class name="ReportGenerationTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:ReportGenerationTest@7e0babb1]" name="setup" is-config="true" duration-ms="6643" started-at="2017-08-08T00:11:38Z" finished-at="2017-08-08T00:11:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:ReportGenerationTest@7e0babb1]" name="initialize" is-config="true" duration-ms="0" started-at="2017-08-08T00:11:44Z" finished-at="2017-08-08T00:11:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="FAIL" signature="testApp_3()[pri:0, instance:ReportGenerationTest@7e0babb1]" name="testApp_3" duration-ms="6262" started-at="2017-08-08T00:11:44Z" finished-at="2017-08-08T00:11:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at ReportGenerationTest.testApp_3(ReportGenerationTest.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testApp_3 -->
        <test-method status="PASS" signature="clearingSetup()[pri:0, instance:ReportGenerationTest@7e0babb1]" name="clearingSetup" is-config="true" duration-ms="2100" started-at="2017-08-08T00:11:51Z" finished-at="2017-08-08T00:11:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearingSetup -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:ReportGenerationTest@7e0babb1]" name="tearDown" is-config="true" duration-ms="584" started-at="2017-08-08T00:11:53Z" finished-at="2017-08-08T00:11:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ReportGenerationTest -->
    </test> <!-- RentalLog3 -->
    <test name="RentalLog5" duration-ms="6654" started-at="2017-08-08T07:11:53Z" finished-at="2017-08-08T07:11:59Z">
      <class name="ReportGenerationTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:ReportGenerationTest@1134affc]" name="setup" is-config="true" duration-ms="2702" started-at="2017-08-08T00:11:53Z" finished-at="2017-08-08T00:11:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="testApp_3()[pri:0, instance:ReportGenerationTest@1134affc]" name="testApp_3" duration-ms="2727" started-at="2017-08-08T00:11:55Z" finished-at="2017-08-08T00:11:58Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at ReportGenerationTest.testApp_3(ReportGenerationTest.java:128)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testApp_3 -->
        <test-method status="PASS" signature="initialize()[pri:0, instance:ReportGenerationTest@1134affc]" name="initialize" is-config="true" duration-ms="0" started-at="2017-08-08T00:11:55Z" finished-at="2017-08-08T00:11:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialize -->
        <test-method status="PASS" signature="clearingSetup()[pri:0, instance:ReportGenerationTest@1134affc]" name="clearingSetup" is-config="true" duration-ms="1116" started-at="2017-08-08T00:11:58Z" finished-at="2017-08-08T00:11:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- clearingSetup -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:ReportGenerationTest@1134affc]" name="tearDown" is-config="true" duration-ms="106" started-at="2017-08-08T00:11:59Z" finished-at="2017-08-08T00:11:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- ReportGenerationTest -->
    </test> <!-- RentalLog5 -->
  </suite> <!-- Selenium Tests -->
</testng-results>
